print("PROJE OZETI")
print("="*50)
print("")
print("TAMAMLANAN ISLEMLER:")
print("1. SQL'den 3607 gercek Turkce sarki verisi cikarildi")
print("2. Akorlar dahil edilerek gelismis preprocessing yapildi")
print("3. 4 farkli model egitildi:")
print("   - Seq2Seq: %80.33 accuracy")
print("   - LSTM: %77.84 accuracy")
print("   - CNN: %81.44 accuracy (EN IYI)")
print("   - Transformer: %73.41 accuracy")
print("")
print("VERI ISTATISTIKLERI:")
print("- Toplam sarki: 3607")
print("- Genre sayisi: 6 (slow, rock, folk, arabesk, pop, rap)")
print("- Kelime dagarcigi: 20,317")
print("- Akor dagarcigi: 109")
print("- Ortalama akor sayisi: 4.5")
print("")
print("EN IYI MODEL: CNN (%81.44 accuracy)")
print("SONUC: Akorlarin eklenmesi beklenen iyilestirmeyi saglamadi")
print("ONERI: CNN modeli bu veri seti icin en uygun secim")
print("")
print("OLUSTURULAN DOSYALAR:")
print("- data/processed/: Islenmis veri setleri")
print("- models/: Egitilmis model dosyalari")
print("- results/: Gorsellestirmeler ve grafikler")
print("- scripts/: Tum Python script'leri")
print("")
print("PROJE BASARIYLA TAMAMLANDI!")
